export const featuresData = [
  { title: 'Notification Viewing',
    subtitle: 'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem stand',
    id: 1,
    gridDesctop: 'grid__item--desktop-1-4',
    gridTablet: 'grid__item--tablet-1-3',
    icon: 'alarm',
  },
  { title: 'Creative Design',
    subtitle: 'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem stand',
    id: 2,
    gridDesctop: 'grid__item--desktop-5-8',
    gridTablet: 'grid__item--tablet-4-6',
    icon: 'lightBulb',
  },
  { title: 'Clean Code',
    subtitle: 'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem stand',
    id: 3,
    gridDesctop: 'grid__item--desktop-9-12',
    gridTablet: 'grid__item--tablet-1-3',
    icon: 'code',
  },
  { title: 'Full Free Video Call',
    subtitle: 'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem stand',
    id: 4,
    gridDesctop: 'grid__item--desktop-1-4',
    gridTablet: 'grid__item--tablet-1-3',
    icon: 'uiVideo',
  },
  { title: 'Great Support',
    subtitle: 'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem stand',
    id: 5,
    gridDesctop: 'grid__item--desktop-5-8',
    gridTablet: 'grid__item--tablet-4-6',
    icon: 'headPhone',
  },
  { title: 'Unlimited Features',
    subtitle: 'Lorem Ipsum is slechts een proeftekst uit het drukkerij- en zetterijwezen. Lorem stand',
    id: 6,
    gridDesctop: 'grid__item--desktop-9-12',
    gridTablet: 'grid__item--tablet-1-3',
    icon: 'heart',
  },  
];
