export const serviceData = [
  { title: 'Easy To Customize',
    subtitle: 'Lorem Ipsum is slechts een preksts uit het drukkerij- en zetterija Lorem Ipsum is de stan.',
    id: 1,
    icon: 'tools',
    gridDesctop: 'grid__item--desktop-1-4',
    gridTablet: 'grid__item--tablet-1-3',
  },
  { title: 'Awesome Design',
    subtitle: 'Lorem Ipsum is slechts een preksts uit het drukkerij- en zetterija Lorem Ipsum is de stan.',
    id: 2,
    icon: 'table',
    gridDesctop: 'grid__item--desktop-5-8',
    gridTablet: 'grid__item--tablet-4-6',
  },
  { title: 'Easy To Use',
    subtitle: 'Lorem Ipsum is slechts een preksts uit het drukkerij- en zetterija Lorem Ipsum is de stan.',
    id: 3,
    icon: 'headPhoneService',
    gridDesctop: 'grid__item--desktop-9-12',
    gridTablet: 'grid__item--tablet-1-3',
  },
];
