export const teamData = [
  { title: 'Sathi Bhuiyan',
    subtitle: 'Lovely Designer',
    id: 1,
    icon: 'sathi',
    gridDesctop: 'grid__item--desktop-1-3',
    gridTablet: 'grid__item--tablet-1-3',
  },
  { title: 'Kausar Al Mamun',
    subtitle: 'Lovely Designer',
    id: 2,
    icon: 'kausar',
    gridDesctop: 'grid__item--desktop-4-6',
    gridTablet: 'grid__item--tablet-4-6',
  },
  { title: 'Nirob Khan',
    subtitle: '3',
    id: 3,
    icon: 'nirob',
    gridDesctop: 'grid__item--desktop-7-9',
    gridTablet: 'grid__item--tablet-1-3',
  },
  { title: 'Salim Rana',
    subtitle: 'Lovely Designer',
    id: 4,
    icon: 'salim',
    gridDesctop: 'grid__item--desktop-10-12',
    gridTablet: 'grid__item--tablet-4-6',
  },
];
